version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    networks:
      - mynet
    ports:
      - '${TEST_DB_PORT}:${TEST_DB_PORT}'

  app:
    container_name: go
    environment:
      - DB_USER=${TEST_DB_USER}
      - DB_PASSWORD=${TEST_DB_PASSWORD}
      - DB_NAME=${TEST_DB_NAME}
      - DB_HOST=${TEST_DB_HOST}
      - DB_PORT=${TEST_DB_PORT}
    build:
      context: .
    ports:
      - 8080:8080
    links:
      - postgres:postgres
    depends_on:
      - "postgres"
    networks:
      - mynet

volumes:
  dbData:

networks:
  mynet:
    driver: bridge