version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    networks:
      - mynet
    ports:
      - 8001:8001
    volumes:
      - './_postgres:/docker-entrypoint'
      - 'dbData:/var/lib/postgresql/data'

  app:
    container_name: go
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=postgres
      - DB_HOST=127.0.0.1
      - DB_PORT=8001
    build:
      context: .
    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres  
    networks:
      - mynet

volumes:
  dbData:

networks:
  mynet:
    driver: bridge