DROP INDEX IF EXISTS "idx_feature_id" CASCADE;

DROP INDEX IF EXISTS "idx_banner_id" CASCADE;

DROP TABLE IF EXISTS "admins" CASCADE;

DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS "bannertags" CASCADE;

DROP TABLE IF EXISTS "banners" CASCADE;

DROP TABLE IF EXISTS "features" CASCADE;

DROP TABLE IF EXISTS "tags" CASCADE;